name: food_client
description: A client for hello fresh recipes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  fpdart: ^0.3.0
  freezed_annotation: ^2.0.3
  http: ^0.13.5
  json_annotation: ^4.6.0
  logging: ^1.1.0
  riverpod_annotation: ^1.0.6
  riverpod_generator: ^1.0.6
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  hive_generator: ^1.1.0
  json_serializable: ^6.3.1
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
