name: commons_graphql
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6
  fpdart: ^0.3.0
  freezed_annotation: ^2.0.3
  graphql: ^5.1.3
  graphql_codegen: ^0.12.0
  http: ^0.13.5
  json_annotation: ^4.6.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.4
  test: ^1.16.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.3.1
  lints: ^2.0.0
